import React from 'react';
import {Product} from "../types/types";

const initProducts: Product[] = [
    {
        "id": 0,
        "name": "Автoмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
        "img": "/public/img/ariel.png",
        "unit": "г",
        "size": "15X28.8",
        "barcode": 4604049097548,
        "manufacturer": "Нэфис",
        "brand": "ARIEL",
        "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
        "type": ["bodyCare"],
    },
    {
        "id": 1,
        "name": "Порошок стиральный Автомат 100 пятен COMPACT",
        "img": "/public/img/biomax.png",
        "unit": "г",
        "size": 1500,
        "barcode": 4604049097548,
        "manufacturer": "Нэфис",
        "brand": "BIMAX",
        "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 132,
        "type": ["bodyCare"],
    },
    {
        "id": 2,
        "name": "Средство для мытья посуды Crystal",
        "img": "/public/img/aos.png",
        "unit": "мл",
        "size": 450,
        "barcode": 4604049097548,
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
        "type": ["bodyCare"],
    },
    {
        "id": 3,
        "name": "Ср-во для мытья посуды Апельсин+мята",
        "img": "/public/img/sorti.png",
        "unit": "мл",
        "size": 450,
        "barcode": 4604049097548,
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
        "type": ["bodyCare"],
    },
    {
        "id": 4,
        "name": "BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
        "img": "/public/img/soup.png",
        "unit": "г",
        "size": 90,
        "barcode": 4604049097548,
        "manufacturer": "BioMio",
        "brand": "BioMio",
        "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
        "type": ["handCare", "faces"],
    },
    {
        "id": 5,
        "name": "BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
        "img": "/public/img/soup.png",
        "unit": "г",
        "size": 90,
        "barcode": 4604049097548,
        "manufacturer": "BioMio",
        "brand": "BioMio",
        "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
        "type": ['handCare', "faceCare"],
    },
    {
        "id": 6,
        "name": "Экологичное туалетное мыло",
        "img": "/public/img/notfoto.png",
        "unit": "г",
        "size": 90,
        "barcode": 4604049097548,
        "manufacturer": "Camay",
        "brand": "Camay",
        "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
        "type": ['handCare', "faceCare"],
    },
    {
        "id": 7,
        "name": "BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
        "img": "/public/img/soup.png",
        "unit": "г",
        "size": 90,
        "barcode": 4604049097548,
        "manufacturer": "BioMio",
        "brand": "BioMio",
        "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
        "type": ['handCare', "faceCare"],
    },
    {
        "id": 8,
        "name": "Экологичное туалетное мыло",
        "img": "/public/img/soup.png",
        "unit": "г",
        "size": 90,
        "barcode": 4604049097548,
        "manufacturer": "Paclan",
        "brand": "Camay",
        "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
        "type": ['handCare'],
    },
    {
        "id": 9,
        "name": "BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
        "img": "/public/img/soup.png",
        "unit": "г",
        "size": 90,
        "barcode": 4604049097548,
        "manufacturer": "Paclan",
        "brand": "Camay",
        "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
        "type": ['handCare'],
    },
    {
        "id": 10,
        "name": "Экологичное туалетное мыло. Литсея и бергамот",
        "img": "/public/img/soup.png",
        "unit": "г",
        "size": 90,
        "barcode": 4604049097548,
        "manufacturer": "Paclan",
        "brand": "Camay",
        "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price":50,
        "type": ['handCare'],
    },
    {
        "id": 11,
        "name": "Экологичное туалетное мыло. Литсея и бергамот",
        "img": "/public/img/notfoto.png",
        "unit": "г",
        "size": 90,
        "barcode": 4604049097548,
        "manufacturer": "Camay",
        "brand": "Camay",
        "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 63,
        "type": ["faceCare"],
    },
    {
        "id": 12,
        "name": "Экологичное туалетное мыло. Литсея и бергамот",
        "img": "/public/img/notfoto.png",
        "unit": "г",
        "size": 90,
        "barcode": 4604049097548,
        "manufacturer": "Camay",
        "brand": "Camay",
        "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
        "type": ["faceCare"],
    },
    {
        "id": 13,
        "name": "Экологичное туалетное мыло. Литсея и бергамот",
        "img": "/public/img/notfoto.png",
        "unit": "г",
        "size": 90,
        "barcode": 4604049097548,
        "manufacturer": "Camay",
        "brand": "Camay",
        "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
        "type": ["faceCare"],
    },
    {
        "id": 14,
        "name": "Экологичное туалетное мыло",
        "img": "/public/img/soup.png",
        "unit": "г",
        "size": 90,
        "barcode": 4604049097548,
        "manufacturer": "Сибиар",
        "brand": "Сибиар",
        "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price":30,
        "type": ['handCare'],
    },
    {
        "id": 15,
        "name": "Экологичное туалетное мыло. Литсея и бергамот",
        "img": "/public/img/soup.png",
        "unit": "г",
        "size": 90,
        "barcode": 4604049097548,
        "manufacturer": "Сибиар",
        "brand": "Сибиар",
        "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
        "type": ['handCare'],
    },
    {
        "id": 16,
        "name": "Экологичное туалетное мыло. Литсея и бергамот",
        "img": "/public/img/soup.png",
        "unit": "г",
        "size": 90,
        "barcode": 4604049097548,
        "manufacturer": "Сибиар",
        "brand": "Сибиар",
        "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
        "type": ['handCare'],
    },
    {
        "id": 17,
        "name": "Экологичное туалетное мыло. Литсея и бергамот",
        "img": "/public/img/soup.png",
        "unit": "г",
        "size": 90,
        "barcode": 4604049097548,
        "manufacturer": "Сибиар",
        "brand": "Сибиар",
        "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
        "type": ['handCare', "faceCare"],
    },
]

export default initProducts;